<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\LastOasisManager.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Payload\Tool_01.payload.zip" LogicalName="Tool01.Native.Payload.Tool_01.payload.zip" />
    <Resource Include="Assets\LastOasisManager.ico" />
  </ItemGroup>

</Project>
